apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: logging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: logging

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
  namespace: logging
data:
  config.alloy: |
    discovery.kubernetes "pod" {
      role = "pod"
    }

    loki.source.kubernetes "pod" {
      targets    = discovery.kubernetes.pod.targets
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.logging.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccount: alloy
      containers:
        - name: alloy
          image: grafana/alloy:latest
          volumeMounts:
            - name: config-pod
              mountPath: /etc/alloy
      volumes:
        - name: config-pod
          configMap:
            name: pod-config
